### PR TITLE
ISSUE-697 ignore invalid REQUEST ITIP local deliveries

### LINKED ISSUE #697: Prevent attendee from updating `ORGANIZER` via PUT in others calendar (short term fix)
### Context

During integration tests, we observed that:

An attendee is able to modify the `ORGANIZER` property via a `PUT` request, and this change is propagated to the organizer's and other attendees.

This behavior is **unexpected and potentially dangerous**, as it breaks scheduling consistency.
This effectively allows an attendee to **impersonate the organizer** or alter ownership of the event.

### 📚 Expected behavior (RFC)

According to RFCs:

  * Attendees are allowed to modify *some* properties
* **RFC 6638 §3.2.4.4**: Servers **MAY restrict** which properties attendees can modify

👉 Therefore: `ORGANIZER` **must not be modifiable by attendees via PUT**

### Proposed behavior

When an attendee sends a `PUT` request modifying `ORGANIZER`:

#### Case 1 — Different organizer

```ics
ORGANIZER:mailto:alice@example.com
→ mailto:bob@example.com
```

👉 **Reject request** (e.g. 403)

#### Case 2 — Same organizer but different formatting

```ics
ORGANIZER:mailto:bob@example.com
→ mailto:BOB@example.com
```

👉 **Normalize to ignore** (do not reject)

### Related

- https://github.com/linagora/twake-calendar-integration-tests
- https://github.com/linagora/esn-sabre/issues/317

### PR DESCRIPTION
**Pull request by vttranlina**
Prevent attendee from updating ORGANIZER via PUT in others calendar
resolve https://github.com/linagora/twake-calendar-side-service/issues/697

### CODE REVIEW

File: calendar-amqp/src/main/java/com/linagora/calendar/amqp/ItipLocalDeliveryConsumer.java [hunk 1]
```diff
@@ -211,26 +219,81 @@ private Mono<Void> processSingleRecipient(ItipLocalDeliveryDTO localDelivery) {
...
         ItipRequest itipRequest = new ItipRequest(localDelivery.uid(), localDelivery.strippedSender(),
             localDelivery.strippedRecipient(), localDelivery.message(), localDelivery.method(), sequence);
         return calDavClient.sendItip(recipientUsername, itipRequest)
             .then();
     }
 
+    private boolean hasInvalidRequestOrganizer(ItipLocalDeliveryDTO localDelivery,
+                                               Calendar calendar,
+                                               Optional<Calendar> oldEventCalendar) {
+        Set<String> currentOrganizers = organizerEmails(calendar);
```
Comment (chibenwa) [inline calendar-amqp/src/main/java/com/linagora/calendar/amqp/ItipLocalDeliveryConsumer.java]: Username as a stronger type, no?

**Review by chibenwa — COMMENTED** [review]
Otherwize overall +1 to me, nice fix
